name: nav_application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.8.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.0.4
  location: ^4.3.0
  google_fonts: ^4.0.1
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4
  intl: ^0.17.0
  graphhooper_route_navigation: ^0.0.3
  get: ^4.6.5
  mapbox_gl: ^0.16.0
  # flutter_mapbox_navigation: ^0.0.26
  # maplibre_gl:
  #     git:
  #       url: https://github.com/maplibre/flutter-maplibre-gl.git
  #       ref: main

dependency_overrides:
  image: ^4.0.17 # Use the version compatible with maplibre_gl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/mapbox.png"

flutter_native_splash:
  color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/image/
    - assets/icon/