name: nav_application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mapbox_gl: ^0.15.0
  flutter_native_splash: ^2.0.2
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  location: ^4.3.0
  carousel_slider: ^4.0.0
  dio: ^4.0.4
  flutter_dotenv: ^5.0.2
  flutter_map: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/mapbox.png"

flutter_native_splash:
  color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/image/